import Head from "next/head";

const Header = () => <header>
    <Head>
        <title>Another Classless CSS Framework</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1>Yet Another Classless CSS Framework</h1>
</header>

export default Header
